name: PluginStaff
main: me.thomasrba.Main
version: 1.0
api-version: 1.20
commands:
  gmc:
    description: Vous permet de passer en mode créatif.
    permission: PluginStaff.gmc
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.
  gms:
    description: Vous permet de passer en mode survie.
    permission: PluginStaff.gms
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.
  kick:
    description: Vous permet de kick un joueur.
    permission: PluginStaff.kick
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.
  vanish:
    description: Vous permet de vous rendre invisible.
    permission: PluginStaff.vanish
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.
  freeze:
    description: Vous permet de figer un joueur.
    permission: PluginStaff.freeze
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.
  kill:
    description: Vous permet de tuer un joueur.
    permission: PluginStaff.kill
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.
  fly:
    description: Vous permet de voler.
    permission: PluginStaff.fly
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.
  invsee:
    description: Vous permet d'ouvrir l'inventaire d'un joueur.
    permission: PluginStaff.invsee
    permission-message: §9§lPluginStaff §cVous n'avez pas la permission de faire cela.